spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/workspace/spring-cloud-config-demo/local-development/config
  profiles:
    active: native

server:
  port: 8888
