services:
  config:
    container_name: config-server
    image: steeltoeoss/config-server
    ports:
      - "8888:8888"
    volumes:
      - ./config:/config
    environment:
      # For file system
      #SPRING_PROFILES_ACTIVE: native
      #SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: "file:///config"

      # For remote
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: "https://github.com/xtreme-brian-shim/config"
      SPRING_CLOUD_CONFIG_SERVER_GIT_SEARCH_PATHS: config
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
  shopping-postgres:
    container_name: shopping-postgres-db
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: acme-shopping
    ports:
      - "5432:5432"

  shopping-mysql:
    container_name: shopping-mysql-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
